import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../components/Layout'
import { Header } from '../components/Header'
import { MovieCard } from '../components/MovieCard'
import { useEffect } from 'react'
import { useRecoilValue, useRecoilState } from 'recoil'
import { data } from '../components/states'
import { RenderMovies } from '../components/RenderMovies'
const Home: NextPage = () => {
  const [movies, setMovies] = useRecoilState(data);
  useEffect(() => {
    const getData = async () => {
      const list = await fetch(
        "https://imdb-api.com/en/API/Top250Movies/k_x8zwoo7z"
      );
      const movieList = await list.json();
      setMovies(movieList.items);
    }
    getData()
  }, [setMovies])
  return (
    <div className="min-h-screen bg-[#f8f8f8]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <RenderMovies />
      </Layout>
    </div>
  );
}

export default Home
