import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { useEffect } from "react";
import { useRecoilState } from "recoil";
import { Titletype, tvs } from "../components/utils/states";
import { Layout } from "../components/Layout";
import { RenderSeries } from "../components/RenderSeries";

const Toptvs: NextPage = () => {
  const [series, setSeries] = useRecoilState(tvs);
  const [type, setType] = useRecoilState(Titletype);
  setType("Series");
  useEffect(() => {
    const getData = async () => {
      const list = await fetch(
        "https://imdb-api.com/en/API/Top250TVs/k_x8zwoo7z"
      );
      const movieList = await list.json();
      setSeries(movieList.items);
    };
    getData();
  }, [setSeries]);
  return (
    <div className="min-h-screen bg-[#f8f8f8]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <RenderSeries />
      </Layout>
    </div>
  );
};
export default Toptvs;
